
//git hub first repository as demo

//creating employee table
CREATE TABLE EMPLOYEE(EMPLOYEE_ID NUMBER(5),NAME VARCHAR2(30),
SALARY NUMBER(6)
);

DESC EMPLOYEE;//gives the description of the table
DESCRIBE EMPLOYEE;

SELECT * FROM EMPLOYEE;

//inserting data into employee table
INSERT INTO EMPLOYEE VALUES(101,'RAMESH',1000);

INSERT INTO EMPLOYEE VALUES(102,'RAJESH',2000);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(103,'GANESH',3000);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(104,'REVATHI',4000);

INSERT INTO EMPLOYEE( EMPLOYEE_ID,NAME,SALARY) VALUES(105,'RAVI',5000);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(106,'KUMAR',6000);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY0 VALUES(107,'RAMA',7000);

SELECT * FROM EMPLOYEE;

// to save it 
COMMIT;

//read operation using SELECT
SELECT EMPLOYEE_ID,NAME FROM EMPLOYEE;

SELECT NAME,SALARY FROM EMPLOYEE;

SELECT NAME,SALARY FROM EMPLOYEE WHERE NAME = 'RAMESH';

SELECT NAME,EMPLOYEE_ID  FROM EMPLOYEE WHERE NAME LIKE 'R%';

SELECT NAME,EMPLOYEE_ID  FROM EMPLOYEE WHERE NAME LIKE 'RA%';

SELECT EMPLOYEE-ID,NAME FROM EMPLOYEE WHERE SALARY > 3000;

SELECT SALARY* 2 FROM EMPLOYEE;//this doesnot modify the table

SELECT SALARY FROM EMPLOYEE;
 
//update operation
UPDATE EMPLOYEE SET SALARY = 2222;//all rows salary wil be updated

SELECT * FROM EMPLOYEE;

//to get the previous values rollback,it only rollback to the last commit
ROLLBACK;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET SALARY = SALARY*2 WHERE NAME LIKE 'R%';

UPDATE EMPLOYEE SET NAME = 'KKKK',SALARY = 6666 WHERE NAME ='KUMAR';

ROLLBACK;

//delete operation
DELETE FROM EMPLOYEE;//it deletes the content of the table employee

SELECT * FROM EMPLOYEE;

DESC EMPLOYEE;

ROLLBACK;

DELETE FROM EMPLOYEE WHERE NAME = 'RAVI';

DROP TABLE EMPLOYEE;//the whole table itself wil be deleted

ROLLBACK;//this does not work from ddl  queries

//list all the tables
SELECT * FROM TAB;

//creating the table
CREATE TABLE EMPLOYEE(EMPLOYEE_ID NUMBER(5),NAME VARCHAR2(30),
SALARY NUMBER(6)
);

DESC EMPLOYEE;


INSERT INTO EMPLOYEE VALUES(101,'RAMESH',1000);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,SALARY) VALUES(102,'RAJESH',2000);

INSERT INTO EMPLOYEE VALUES(&EMPLOYEE_ID,&NAME,&SALARY);//can insert in this way also
enter value for employee_id:103
enter value for name:GANESH
enter value for salary:3000

//altering or modifying the table
ALTER TABLE EMPLOYEE ADD(PASSWORD VARCHAR(20));

ALTER TABLE EMPLOYEE DROP(PASSWORD);

ALTER TABLE EMPLOYEE ADD(PASSWORD VARCHAR(20));

ALTER TABLE EMPLOYEE MODIFY(NAME VARCHAR(30));

UPDATE EMPLOYEE SET PASSWORD = 'RAJ' WHERE EMPLOYEE_ID = 102;

UPDATE EMPLOYEE SET PASSWORD = 'GAN' WHERE NAME = 'GANESH';

//ascending order
SELECT * FROM EMPLOYEE ORDER BY SALARY;

//descending order
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;

